const PRODUCT_SCHEMA_UTILS = Object.freeze({
    NAME_MAX_LENGTH:52,
    NAME_MIN_LENGTH:16,
    DESC_MAX_LENGTH:520,
    PRICE_MIN_VALUE:100,
    PRICE_MAX_VALUE:50000,
    PRICE_MAX_LENGTH:5,
})

export default PRODUCT_SCHEMA_UTILS;